spring:
  application:
    name: inventory


  datasource:
    url: jdbc:h2:mem:inventoriesdb
    username: sa
    password: sc
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    #    hibernate:
    #      ddl-auto: update
  h2:
    console:
      enabled: true
  cloud:
    openfeign:
      client:
        config:
          product-service:
            url: http://localhost:8082
            connectTimeout: 2000
            readTimeout: 5000

resilience4j.retry:
  instances:
    productServiceRetry:
      max-attempts: 3
      wait-duration: 400ms
      retry-exceptions:
        - feign.FeignException$InternalServerError
        - feign.FeignException$ServiceUnavailable
        - feign.RetryableException


logging:
  level:
    io.github.resilience4j.retry: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
server:
  port: 8081

security:
  api-key: my-secret-key