spring:
  application:
    name: inventory


  datasource:
    url: jdbc:h2:mem:inventoriesdb
    username: sa
    password: sc
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  cloud:
    openfeign:
      client:
        config:
          product-service:
            url: ${PRODUCT_SERVICE_URL:http://localhost:8082}
            connectTimeout: 2000
            readTimeout: 5000

resilience4j.retry:
  instances:
    productServiceRetry:
      max-attempts: 3
      wait-duration: 400ms
      retry-exceptions:
        - feign.FeignException$InternalServerError
        - feign.FeignException$ServiceUnavailable
        - feign.RetryableException


logging:
  level:
    root: INFO
  pattern:
    console: '{"time":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","service":"%X{spring.application.name}","thread":"%t","logger":"%c","message":"%m"}%n'


management:
  endpoints:
    web:
      exposure:
        include: health, metrics
    endpoint:
      health:
        show-details: always
server:
  port: 8081

security:
  api-key: ${SPRING_SECURITY_API_KEY:secret-key}